#
# Makefile for Phoenix-RTOS kernel (AArch64 HAL ZynqMP)
#
# Copyright 2024 Phoenix Systems
#

OBJS += $(addprefix $(PREFIX_O)hal/aarch64/zynqmp/, console.o zynqmp.o)
OBJS += $(addprefix $(PREFIX_O)hal/platform/zynq/, timer_ttc.o)
