#
# Makefile for HAL ARM common functions
#
# Copyright 2023 Phoenix Systems
#

# TODO handle other common ARM stuff (e.g GIC) and
# select relevant components here

OBJS += $(addprefix $(PREFIX_O)hal/arm/, nvic.o scb.o)
