#
# Makefile for phoenix-rtos-kernel/trace
#
# Copyright 2025 Phoenix Systems
# Author: Adam Greloch
#

OBJS += $(addprefix $(PREFIX_O)trace/, trace-ctf.o buffer.o)

# include trace/$(TARGET_SUFF)/Makefile
