#
# Makefile for Phoenix-RTOS kernel (ARMv7 HAL)
#
# Copyright 2016-2017, 2019-2020 Phoenix Systems
#

CFLAGS += -Ihal/armv7m/imxrt/10xx

OBJS += $(addprefix $(PREFIX_O)hal/armv7m/imxrt/10xx/, console.o imxrt10xx.o)
