#
# Makefile for Phoenix-RTOS kernel (ARMv8 HAL)
#
# Copyright 2016-2017, 2019-2020, 2022 Phoenix Systems
#

CFLAGS += -Ihal/armv8m/nrf/91

OBJS += $(addprefix $(PREFIX_O)hal/armv8m/nrf/91/, nrf91.o console.o timer.o)
