#
# Makefile for Phoenix-RTOS kernel (ARMv8 HAL)
#
# Copyright 2016-2017, 2019-2020, 2022, 2024 Phoenix Systems
#

CFLAGS += -Ihal/armv8m/mcx/n94x

OBJS += $(addprefix $(PREFIX_O)hal/armv8m/mcx/n94x/, mcxn94x.o console.o timer.o)
