#
# Makefile for Phoenix-RTOS kernel (ARMv8-M HAL STM32H5)
#
# Copyright 2016-2017, 2019-2025 Phoenix Systems
#

CFLAGS += -Ihal/armv8m/stm32/h5

OBJS += $(addprefix $(PREFIX_O)hal/armv8m/stm32/h5/, _init.o stm32h5.o timer.o)
