#
# Makefile for Phoenix-RTOS kernel (sparcv8leon-gr740 HAL)
#
# Copyright 2025 Phoenix Systems
#

include hal/tlb/Makefile

OBJS += $(addprefix $(PREFIX_O)hal/$(TARGET_SUFF)/gaisler/$(TARGET_SUBFAMILY)/, _init.o gr740.o)
