#
# Makefile for phoenix-rtos-kernel/lib
#
# Copyright 2020 Phoenix Systems
# Author: Pawel Pisarczyk
#

OBJS += $(addprefix $(PREFIX_O)lib/, assert.o printf.o bsearch.o rand.o rb.o list.o cbuffer.o strutil.o idtree.o)

