#
# Makefile for Phoenix-RTOS kernel (ARMv7A HAL Zynq-7000)
#
# Copyright 2021 Phoenix Systems
#

OBJS += $(addprefix $(PREFIX_O)hal/armv7a/zynq7000/, _init.o console.o zynq.o pmap.o timer.o interrupts.o)
