#
# Makefile for Phoenix-RTOS kernel (sparcv8leon-generic HAL)
#
# Copyright 2024 Phoenix Systems
#

include hal/tlb/Makefile

OBJS += $(addprefix $(PREFIX_O)hal/$(TARGET_SUFF)/gaisler/$(TARGET_SUBFAMILY)/, generic.o _init.o)
