#
# Makefile for Phoenix-RTOS kernel (ARMv7 HAL)
#
# Copyright 2016-2017, 2019-2020 Phoenix Systems
#

CFLAGS += -Ihal/armv7m/imxrt/117x

OBJS += $(addprefix $(PREFIX_O)hal/armv7m/imxrt/117x/, console.o imxrt117x.o)
