#
# Makefile for Phoenix-RTOS kernel (ARMv8-R HAL MPS3 AN536)
#
# Copyright 2024 Phoenix Systems
#

OBJS += $(addprefix $(PREFIX_O)hal/armv8r/mps3an536/, _init.o console.o interrupts.o mps3an536.o timer.o)

