#
# Makefile for Phoenix-RTOS kernel (sparcv8leon3-gr712rc HAL)
#
# Copyright 2023 Phoenix Systems
#

include hal/tlb/Makefile

OBJS += $(addprefix $(PREFIX_O)hal/$(TARGET_SUFF)/gaisler/$(TARGET_SUBFAMILY)/, gr712rc.o _init.o)
