#
# Makefile for Phoenix-RTOS kernel (ARMv8-M HAL STM32N6)
#
# Copyright 2016-2017, 2019-2025 Phoenix Systems
#

CFLAGS += -Ihal/armv8m/stm32/n6

OBJS += $(addprefix $(PREFIX_O)hal/armv8m/stm32/n6/, stm32n6.o console.o timer.o)
