/*
 * Phoenix-RTOS
 *
 * Operating system kernel
 *
 * STM32N6 basic peripherals control functions
 *
 * Copyright 2025 Phoenix Systems
 * Author: Jacek Maksymowicz
 *
 * This file is part of Phoenix-RTOS.
 *
 * %LICENSE%
 */

#ifndef _PHOENIX_ARCH_STM32N6_H_
#define _PHOENIX_ARCH_STM32N6_H_


#define PCTL_REBOOT_MAGIC 0xaa55aa55UL

/* STM32N6 device identifiers */
enum {
	pctl_dev_gpdma1 = 0x4,
	pctl_dev_adc12,
	pctl_dev_ramcfg = 0x2c,
	pctl_dev_mdf1 = 0x30,
	pctl_dev_adf1,
	pctl_dev_rng = 0x40,
	pctl_dev_hash,
	pctl_dev_cryp,
	pctl_dev_saes = 0x44,
	pctl_dev_pka = 0x48,
	pctl_dev_rifsc,
	pctl_dev_iac,
	pctl_dev_risaf = 0x4e,
	pctl_dev_gpioa = 0x60,
	pctl_dev_gpiob,
	pctl_dev_gpioc,
	pctl_dev_gpiod,
	pctl_dev_gpioe,
	pctl_dev_gpiof,
	pctl_dev_gpiog,
	pctl_dev_gpioh,
	pctl_dev_gpion = 0x6d,
	pctl_dev_gpioo,
	pctl_dev_gpiop,
	pctl_dev_gpioq,
	pctl_dev_pwr = 0x72,
	pctl_dev_crc,
	pctl_dev_hpdma1 = 0x80,
	pctl_dev_dma2d,
	pctl_dev_jpeg = 0x83,
	pctl_dev_fmc,
	pctl_dev_xspi1,
	pctl_dev_pssi,
	pctl_dev_sdmmc2,
	pctl_dev_sdmmc1,
	pctl_dev_xspi2 = 0x8c,
	pctl_dev_xspim,
	pctl_dev_mce1,
	pctl_dev_mce2,
	pctl_dev_mce3,
	pctl_dev_xspi3,
	pctl_dev_mce4,
	pctl_dev_gfxmmu,
	pctl_dev_gpu,
	pctl_dev_eth1mac = 0x96,
	pctl_dev_eth1tx,
	pctl_dev_eth1rx,
	pctl_dev_eth1,
	pctl_dev_otg1,
	pctl_dev_otgphy1,
	pctl_dev_otgphy2,
	pctl_dev_otg2,
	pctl_dev_npucache,
	pctl_dev_npu,
	pctl_dev_tim2 = 0xa0,
	pctl_dev_tim3,
	pctl_dev_tim4,
	pctl_dev_tim5,
	pctl_dev_tim6,
	pctl_dev_tim7,
	pctl_dev_tim12,
	pctl_dev_tim13,
	pctl_dev_tim14,
	pctl_dev_lptim1,
	pctl_dev_wwdg = 0xab,
	pctl_dev_tim10,
	pctl_dev_tim11,
	pctl_dev_spi2,
	pctl_dev_spi3,
	pctl_dev_spdifrx1,
	pctl_dev_usart2,
	pctl_dev_usart3,
	pctl_dev_uart4,
	pctl_dev_uart5,
	pctl_dev_i2c1,
	pctl_dev_i2c2,
	pctl_dev_i2c3,
	pctl_dev_i3c1,
	pctl_dev_i3c2,
	pctl_dev_uart7 = 0xbe,
	pctl_dev_uart8,
	pctl_dev_mdios = 0xc5,
	pctl_dev_fdcan = 0xc8,
	pctl_dev_ucpd1 = 0xd2,
	pctl_dev_tim1 = 0xe0,
	pctl_dev_tim8,
	pctl_dev_usart1 = 0xe4,
	pctl_dev_usart6,
	pctl_dev_uart9,
	pctl_dev_usart10,
	pctl_dev_spi1 = 0xec,
	pctl_dev_spi4,
	pctl_dev_tim18 = 0xef,
	pctl_dev_tim15,
	pctl_dev_tim16,
	pctl_dev_tim17,
	pctl_dev_tim9,
	pctl_dev_spi5,
	pctl_dev_sai1,
	pctl_dev_sai2,
	pctl_dev_dft = 0x102,
	pctl_dev_hdp = 0x122,
	pctl_dev_lpuart1,
	pctl_dev_spi6 = 0x125,
	pctl_dev_i2c4 = 0x127,
	pctl_dev_lptim2 = 0x129,
	pctl_dev_lptim3,
	pctl_dev_lptim4,
	pctl_dev_lptim5,
	pctl_dev_vrefbuf = 0x12f,
	pctl_dev_rtc,
	pctl_dev_rtcapb,
	pctl_dev_r2gret = 0x136,
	pctl_dev_r2gnpu,
	pctl_dev_serf = 0x13f,
	pctl_dev_syscfg = 0x140,
	pctl_dev_bsec,
	pctl_dev_dts,
	pctl_dev_busperfm = 0x144,
	pctl_dev_ltdc,
	pctl_dev_dcmipp,
	pctl_dev_gfxtim = 0x164,
	pctl_dev_venc,
	pctl_dev_csi,
};


/* STM32N6 independent device clocks */
enum ipclks {
	pctl_ipclk_adf1sel = 0,
	pctl_ipclk_adc12sel,
	pctl_ipclk_adcpre,
	pctl_ipclk_dcmippsel,
	pctl_ipclk_eth1ptpsel,
	pctl_ipclk_eth1ptpdiv,
	pctl_ipclk_eth1pwrdownack,
	pctl_ipclk_eth1clksel,
	pctl_ipclk_eth1sel,
	pctl_ipclk_eth1refclksel,
	pctl_ipclk_eth1gtxclksel,
	pctl_ipclk_fdcansel,
	pctl_ipclk_fmcsel,
	pctl_ipclk_dftsel,
	pctl_ipclk_i2c1sel,
	pctl_ipclk_i2c2sel,
	pctl_ipclk_i2c3sel,
	pctl_ipclk_i2c4sel,
	pctl_ipclk_i3c1sel,
	pctl_ipclk_i3c2sel,
	pctl_ipclk_ltdcsel,
	pctl_ipclk_mco1sel,
	pctl_ipclk_mco1pre,
	pctl_ipclk_mco2sel,
	pctl_ipclk_mco2pre,
	pctl_ipclk_mdf1sel,
	pctl_ipclk_xspi1sel,
	pctl_ipclk_xspi2sel,
	pctl_ipclk_xspi3sel,
	pctl_ipclk_otgphy1sel,
	pctl_ipclk_otgphy1ckrefsel,
	pctl_ipclk_otgphy2sel,
	pctl_ipclk_otgphy2ckrefsel,
	pctl_ipclk_persel,
	pctl_ipclk_pssisel,
	pctl_ipclk_rtcsel,
	pctl_ipclk_rtcpre,
	pctl_ipclk_sai1sel,
	pctl_ipclk_sai2sel,
	pctl_ipclk_sdmmc1sel,
	pctl_ipclk_sdmmc2sel,
	pctl_ipclk_spdifrx1sel,
	pctl_ipclk_spi1sel,
	pctl_ipclk_spi2sel,
	pctl_ipclk_spi3sel,
	pctl_ipclk_spi4sel,
	pctl_ipclk_spi5sel,
	pctl_ipclk_spi6sel,
	pctl_ipclk_lptim1sel,
	pctl_ipclk_lptim2sel,
	pctl_ipclk_lptim3sel,
	pctl_ipclk_lptim4sel,
	pctl_ipclk_lptim5sel,
	pctl_ipclk_usart1sel,
	pctl_ipclk_usart2sel,
	pctl_ipclk_usart3sel,
	pctl_ipclk_uart4sel,
	pctl_ipclk_uart5sel,
	pctl_ipclk_usart6sel,
	pctl_ipclk_uart7sel,
	pctl_ipclk_uart8sel,
	pctl_ipclk_uart9sel,
	pctl_ipclk_usart10sel,
	pctl_ipclk_lpuart1sel,
	pctl_ipclks_count,
};


/* STM32N6 Interrupt numbers */
enum {
	pvd_pvm_irq = 16,
	dts_irq = 18,
	rcc_irq,
	lockup_irq,
	cache_ecc_irq,
	tcm_ecc_irq,
	bck_ecc_irq,
	fpu_irq,
	rtc_s_irq = 26,
	tamp_irq,
	rifsc_tamper_irq,
	iac_irq,
	rcc_s_irq,
	rtc_irq = 32,
	wdgls_early_irq = 34,
	wwdg_early_irq,
	exti0_irq,
	exti1_irq,
	exti2_irq,
	exti3_irq,
	exti4_irq,
	exti5_irq,
	exti6_irq,
	exti7_irq,
	exti8_irq,
	exti9_irq,
	exti10_irq,
	exti11_irq,
	exti12_irq,
	exti13_irq,
	exti14_irq,
	exti15_irq,
	hash_irq = 55,
	rng_irq,
	adc12_irq = 62,
	csi_dbg_irq,
	dcmipp_irq,
	pahb_err_irq = 68,
	npu_end_of_epoch_irq,
	npu1_irq,
	npu2_irq,
	npu3_irq,
	npucache_irq,
	ltdc_lo_irq,
	ltdc_lo_err_irq,
	dma2d_irq,
	jpeg_irq,
	venc_irq,
	gfxmmu_irq,
	gfxtim_irq,
	gpu2d_irq,
	gpu2d_error_irq,
	gpu_cache_irq,
	hpdma1_ch0_irq,
	hpdma1_ch1_irq,
	hpdma1_ch2_irq,
	hpdma1_ch3_irq,
	hpdma1_ch4_irq,
	hpdma1_ch5_irq,
	hpdma1_ch6_irq,
	hpdma1_ch7_irq,
	hpdma1_ch8_irq,
	hpdma1_ch9_irq,
	hpdma1_ch10_irq,
	hpdma1_ch11_irq,
	hpdma1_ch12_irq,
	hpdma1_ch13_irq,
	hpdma1_ch14_irq,
	hpdma1_ch15_irq,
	gpdma1_ch0_irq,
	gpdma1_ch1_irq,
	gpdma1_ch2_irq,
	gpdma1_ch3_irq,
	gpdma1_ch4_irq,
	gpdma1_ch5_irq,
	gpdma1_ch6_irq,
	gpdma1_ch7_irq,
	gpdma1_ch8_irq,
	gpdma1_ch9_irq,
	gpdma1_ch10_irq,
	gpdma1_ch11_irq,
	gpdma1_ch12_irq,
	gpdma1_ch13_irq,
	gpdma1_ch14_irq,
	gpdma1_ch15_irq,
	i2c1_ev_irq,
	i2c1_er_irq,
	i2c2_ev_irq,
	i2c2_er_irq,
	i2c3_ev_irq,
	i2c3_er_irq,
	i2c4_ev_irq,
	i2c4_er_irq,
	i3c1_ev_irq,
	i3c1_er_irq,
	i3c2_ev_irq,
	i3c2_er_irq,
	tim1_brk_irq,
	tim1_up_irq,
	tim1_trg_ccu_irq,
	tim1_cc_irq,
	tim2_irq,
	tim3_irq,
	tim4_irq,
	tim5_irq,
	tim6_irq,
	tim7_irq,
	tim8_brk_irq,
	tim8_up_irq,
	tim8_trg_ccu_irq,
	tim8_cc_irq,
	tim9_irq,
	tim10_irq,
	tim11_irq,
	tim12_irq,
	tim13_irq,
	tim14_irq,
	tim15_irq,
	tim16_irq,
	tim17_irq,
	tim18_irq,
	lptim1_irq,
	lptim2_irq,
	lptim3_irq,
	lptim4_irq,
	lptim5_irq,
	adf1_flt0_irq,
	mdf1_flt0_irq,
	mdf1_flt1_irq,
	mdf1_flt2_irq,
	mdf1_flt3_irq,
	mdf1_flt4_irq,
	mdf1_flt5_irq,
	sai1_a_irq,
	sai1_b_irq,
	sai2_a_irq,
	sai2_b_irq,
	spdifrx_irq,
	spi1_irq,
	spi2_irq,
	spi3_irq,
	spi4_irq,
	spi5_irq,
	spi6_irq,
	usart1_irq,
	usart2_irq,
	usart3_irq,
	uart4_irq,
	uart5_irq,
	usart6_irq,
	uart7_irq,
	uart8_irq,
	uart9_irq,
	usart10_irq,
	lpuart1_irq,
	xspi1_irq,
	xspi2_irq,
	xspi3_irq,
	fmc_irq,
	sdmmc1_irq,
	sdmmc2_irq,
	ucpd_irq,
	otg1_irq,
	otg2_irq,
	eth1_irq,
	fdcan1_it0_irq,
	fdcan1_it1_irq,
	fdcan2_it0_irq,
	fdcan2_it1_irq,
	fdcan3_it0_irq,
	fdcan3_it1_irq,
	fdcan_cu_irq,
	mdios_irq,
	dcmi_pssi_irq,
	wakeup_pin_irq,
	cti0_irq,
	cti1_irq,
	ltdc_up_irq = 209,
	ltdc_up_err_irq,
};


typedef struct {
	enum {
		pctl_set = 0,
		pctl_get,
	} action;

	enum {
		pctl_devclk = 0,
		pctl_cpuclk,
		pctl_perclk,
		pctl_reboot,
	} type;

	union {
		struct {
			unsigned int dev;   /* one of pctl_dev_* enum values */
			unsigned int state; /* 1 - clock enabled; 0 - clock disabled */
		} devclk;

		struct {
			unsigned int hz;
		} perclk;

		struct {
			unsigned int hz;
		} cpuclk;

		struct {
			unsigned int magic;
			unsigned int reason;
		} reboot;
	};
} __attribute__((packed)) platformctl_t;


#endif
