#
# Makefile for Phoenix-RTOS kernel (ARMv7A HAL imx6ull)
#
# Copyright 2021 Phoenix Systems
#

OBJS += $(addprefix $(PREFIX_O)hal/armv7a/imx6ull/, _init.o console.o imx6ull.o pmap.o syspage.o timer.o interrupts.o)

