#
# Makefile for Phoenix-RTOS kernel (RISCV64 HAL)
#
# Copyright 2018, 2020 Phoenix Systems
#

OBJS += $(addprefix $(PREFIX_O)hal/riscv64/, _init.o string.o _interrupts.o syspage.o hal.o spinlock.o interrupts.o cpu.o pmap.o dtb.o timer.o exceptions.o plic.o)

OBJS += $(PREFIX_O)hal/riscv64/console.o

